# Setup
title:               PortaltoNepal  
tagline:             'Revolutionalising Nepal'
description:         'Made by Nepal, for Nepal, in Nepal.'
url:                 'https://aloks.com.np/' # Domain/Subdomain
baseurl:              '' # path
paginate:            5
permalink:           /blog/:title/
collections:
  posts:
    permalink: "/blog/:title/"
    output: true
  board:
    permalink: "/:collection/:path/"
    output: true
  notes:
    permalink: "/:collection/:path/"
    output: true

# About/contact
author:
  name:              PortaltoNepal
  url:               https://portaltonepal.com
  email:             support@portaltonepal.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-175637145-1
